package jambalaya.model.auto;

import java.time.LocalDateTime;
import java.util.List;

import jambalaya.model.Artist;
import jambalaya.model.Painting;

import org.apache.cayenne.CayenneDataObject;

import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.exp.Expression;

import org.apache.cayenne.exp.Property;

/**
 * Class _Artist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Artist extends CayenneDataObject {

    public static final String ENTITY_NAME = "Artist";

    public static final Property<java.time.LocalDateTime> CREATION_DATE = Property.create( "creationDate", java.time.LocalDateTime.class );
    public static final Property<java.time.LocalDateTime> MODIFICATION_DATE = Property.create( "modificationDate", java.time.LocalDateTime.class );
    public static final Property<java.lang.String> NAME = Property.create( "name", java.lang.String.class );
    public static final Property<java.lang.String> UNIQUE_ID = Property.create( "uniqueID", java.lang.String.class );
    public static final Property<jambalaya.model.Painting> PAINTINGS = Property.create( "paintings", jambalaya.model.Painting.class );

    public static final String ID_PK_COLUMN = "id";

	public static Artist createArtist(ObjectContext oc
	) {
		Artist result = new Artist();
		oc.registerNewObject(result);
		return result;
	}
	
    public void setCreationDate(LocalDateTime creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public LocalDateTime creationDate() {
        return (LocalDateTime)readProperty("creationDate");
    }

    public void setModificationDate(LocalDateTime modificationDate) {
        writeProperty("modificationDate", modificationDate);
    }
    public LocalDateTime modificationDate() {
        return (LocalDateTime)readProperty("modificationDate");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String name() {
        return (String)readProperty("name");
    }

    public void setUniqueID(String uniqueID) {
        writeProperty("uniqueID", uniqueID);
    }
    public String uniqueID() {
        return (String)readProperty("uniqueID");
    }

    public void addToPaintings(Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    public Painting createPaintingsRelationship() {
    	Painting obj = getObjectContext().newObject(Painting.class);
        addToManyTarget("paintings", obj, true);
        return obj;
    }
    public void deletePaintingsRelationship(Painting obj) {
        removeToManyTarget("paintings", obj, true);
        getObjectContext().deleteObject(obj);
    }
    @SuppressWarnings("unchecked")
    public List<Painting> paintings() {
        return (List<Painting>)readProperty("paintings");
    }
    
    public List<Painting> paintings(Expression expression) {
		return expression.filterObjects(paintings());
	}


}