package jambalaya.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jambalaya.model.Artist;
import jambalaya.model.Painting;
import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.exp.Expression;
import org.apache.cayenne.query.Ordering;
import org.apache.cayenne.query.SelectQuery;

import org.apache.cayenne.exp.Property;

/**
 * Class _Artist was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Artist extends CayenneDataObject {

    public static final String ENTITY_NAME = "Artist";

    public static final Property<java.util.Date> CREATION_DATE = Property.create( "creationDate", java.util.Date.class );
    public static final Property<java.util.Date> MODIFICATION_DATE = Property.create( "modificationDate", java.util.Date.class );
    public static final Property<java.lang.String> NAME = Property.create( "name", java.lang.String.class );
    public static final Property<java.lang.String> UNIQUE_ID = Property.create( "uniqueID", java.lang.String.class );
    public static final Property<jambalaya.model.Painting> PAINTINGS = Property.create( "paintings", jambalaya.model.Painting.class );

    public static final String ID_PK_COLUMN = "id";

	public static Artist createArtist(ObjectContext oc
	) {
		Artist result = new Artist();
		oc.registerNewObject(result);
		return result;
	}
	
    public void setCreationDate(Date creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public Date creationDate() {
        return (Date)readProperty("creationDate");
    }

    public void setModificationDate(Date modificationDate) {
        writeProperty("modificationDate", modificationDate);
    }
    public Date modificationDate() {
        return (Date)readProperty("modificationDate");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String name() {
        return (String)readProperty("name");
    }

    public void setUniqueID(String uniqueID) {
        writeProperty("uniqueID", uniqueID);
    }
    public String uniqueID() {
        return (String)readProperty("uniqueID");
    }

    public void addToPaintings(Painting obj) {
        addToManyTarget("paintings", obj, true);
    }
    public void removeFromPaintings(Painting obj) {
        removeToManyTarget("paintings", obj, true);
    }
    public Painting createPaintingsRelationship() {
    	Painting obj = getObjectContext().newObject(Painting.class);
        addToManyTarget("paintings", obj, true);
        return obj;
    }
    public void deletePaintingsRelationship(Painting obj) {
        removeToManyTarget("paintings", obj, true);
        getObjectContext().deleteObject(obj);
    }
    @SuppressWarnings("unchecked")
    public List<Painting> paintings() {
        return (List<Painting>)readProperty("paintings");
    }
    
    public List<Painting> paintings(Expression expression) {
		return expression.filterObjects(paintings());
	}



	@SuppressWarnings("unchecked")
	public static java.util.List<Artist> fetchAll( ObjectContext oc ) {
		SelectQuery<Artist> q = new SelectQuery<>( Artist.class );
  		return oc.performQuery( q );
 	}
 	
	@SuppressWarnings("unchecked")
 	public static java.util.List<Artist> fetch( ObjectContext oc, Expression expression ) {
  		SelectQuery<Artist> q = new SelectQuery<>( Artist.class, expression );
  		return oc.performQuery( q );
 	}

	@SuppressWarnings("unchecked")
 	public static java.util.List<Artist> fetch( ObjectContext oc, Expression expression, java.util.List<Ordering> orderings ) {
  		SelectQuery<Artist> q = new SelectQuery<>( Artist.class, expression );

  		if ( orderings != null ) {
   			for( Ordering ordering : orderings ) {
    			q.addOrdering( ordering );
   			}
  		}

  		return oc.performQuery( q );
 	}
 	
 	@SuppressWarnings("unchecked")
 	public static java.util.List<Artist> fetchAll( ObjectContext oc, java.util.List<Ordering> orderings ) {
  		SelectQuery<Artist> q = new SelectQuery<>( Artist.class);

  		if ( orderings != null ) {
   			for( Ordering ordering : orderings ) {
    			q.addOrdering( ordering );
   			}
  		}

  		return oc.performQuery( q );
 	}
 	
 	
	public static Artist fetchOne(ObjectContext oc, Expression expression) {
		java.util.List<Artist> objects = fetch(oc, expression);
		Artist obj;
		int count = objects.size();
		if (count == 0) {
			obj = null;
		} else if (count == 1) {
			obj = objects.get(0);
		} else {
			throw new IllegalStateException("There was more than one Artist that matched the qualifier '" + expression + "'.");
		}
		return obj;
	}
}