package jambalaya.model.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;

import jambalaya.model.Artist;
import jambalaya.model.Painting;
import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.exp.Expression;
import org.apache.cayenne.query.Ordering;
import org.apache.cayenne.query.SelectQuery;

import org.apache.cayenne.exp.Property;

/**
 * Class _Painting was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Painting extends CayenneDataObject {

    public static final String ENTITY_NAME = "Painting";

    public static final Property<java.time.LocalDateTime> CREATION_DATE = Property.create( "creationDate", java.time.LocalDateTime.class );
    public static final Property<java.time.LocalDateTime> MODIFICATION_DATE = Property.create( "modificationDate", java.time.LocalDateTime.class );
    public static final Property<java.lang.String> NAME = Property.create( "name", java.lang.String.class );
    public static final Property<java.lang.String> UNIQUE_ID = Property.create( "uniqueID", java.lang.String.class );
    public static final Property<jambalaya.model.Artist> ARTIST = Property.create( "artist", jambalaya.model.Artist.class );

    public static final String ID_PK_COLUMN = "id";

	public static Painting createPainting(ObjectContext oc
	) {
		Painting result = new Painting();
		oc.registerNewObject(result);
		return result;
	}
	
    public void setCreationDate(LocalDateTime creationDate) {
        writeProperty("creationDate", creationDate);
    }
    public LocalDateTime creationDate() {
        return (LocalDateTime)readProperty("creationDate");
    }

    public void setModificationDate(LocalDateTime modificationDate) {
        writeProperty("modificationDate", modificationDate);
    }
    public LocalDateTime modificationDate() {
        return (LocalDateTime)readProperty("modificationDate");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String name() {
        return (String)readProperty("name");
    }

    public void setUniqueID(String uniqueID) {
        writeProperty("uniqueID", uniqueID);
    }
    public String uniqueID() {
        return (String)readProperty("uniqueID");
    }

    public void setArtist(Artist artist) {
        setToOneTarget("artist", artist, true);
    }
    public Artist createArtistRelationship() {
        Artist obj = getObjectContext().newObject(Artist.class);
        setToOneTarget("artist", obj, true);
        return obj;
    }

    public Artist artist() {
        return (Artist)readProperty("artist");
    }



	@SuppressWarnings("unchecked")
	public static java.util.List<Painting> fetchAll( ObjectContext oc ) {
		SelectQuery<Painting> q = new SelectQuery<>( Painting.class );
  		return oc.performQuery( q );
 	}
 	
	@SuppressWarnings("unchecked")
 	public static java.util.List<Painting> fetch( ObjectContext oc, Expression expression ) {
  		SelectQuery<Painting> q = new SelectQuery<>( Painting.class, expression );
  		return oc.performQuery( q );
 	}

	@SuppressWarnings("unchecked")
 	public static java.util.List<Painting> fetch( ObjectContext oc, Expression expression, java.util.List<Ordering> orderings ) {
  		SelectQuery<Painting> q = new SelectQuery<>( Painting.class, expression );

  		if ( orderings != null ) {
   			for( Ordering ordering : orderings ) {
    			q.addOrdering( ordering );
   			}
  		}

  		return oc.performQuery( q );
 	}
 	
 	@SuppressWarnings("unchecked")
 	public static java.util.List<Painting> fetchAll( ObjectContext oc, java.util.List<Ordering> orderings ) {
  		SelectQuery<Painting> q = new SelectQuery<>( Painting.class);

  		if ( orderings != null ) {
   			for( Ordering ordering : orderings ) {
    			q.addOrdering( ordering );
   			}
  		}

  		return oc.performQuery( q );
 	}
 	
 	
	public static Painting fetchOne(ObjectContext oc, Expression expression) {
		java.util.List<Painting> objects = fetch(oc, expression);
		Painting obj;
		int count = objects.size();
		if (count == 0) {
			obj = null;
		} else if (count == 1) {
			obj = objects.get(0);
		} else {
			throw new IllegalStateException("There was more than one Painting that matched the qualifier '" + expression + "'.");
		}
		return obj;
	}
}